spring.application.name=student-crud
server.port=9000

spring.cloud.gateway.routes[0].id=connection-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/connection/**